name: 'BingPic'

on:
  schedule:
    - cron: '00 16 * * *'

jobs:
  bot: 
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with: 
          python-version: 3.11
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Config
        run: |
          git config --local user.email "raoyirui2006@163.com"
          git config --local user.name "Siefe"
      - name: 'Start Python'
        run: python bing.py
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
